LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := dfu-util
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/bin
LOCAL_SRC_FILES := dfu-util
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := LevrPlus
LOCAL_SRC_FILES := LevrPlus.jar
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_TAGS := optional
#LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_DX_FLAGS := --core-library
#LOCAL_DEX_PREOPT := false
LOCAL_MODULE_OWNER := letv
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE             := libLeVRUnityPlus
LOCAL_MODULE_TAGS        := optional
LOCAL_SRC_FILES          := libLeVRUnityPlus.so
LOCAL_MODULE_CLASS       := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX      := .so
LOCAL_MODULE_OWNER       := letv
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_PATH        := $(PRODUCT_OUT)/system/lib
LOCAL_MULTILIB           := 32
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := lvrinfo.xml
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/etc
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := svrinfo.xml
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/etc
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)
